// <auto-generated />
using System;
using Infrastructure.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.Checkin", b =>
                {
                    b.Property<long>("CheckinId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("CheckinID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("CheckinId"));

                    b.Property<DateTime>("CheckinTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<long>("EmployeeId")
                        .HasColumnType("bigint")
                        .HasColumnName("EmployeeID");

                    b.Property<string>("Notes")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("CheckinId")
                        .HasName("PK__Checkins__F3C85D51E292FB00");

                    b.HasIndex(new[] { "EmployeeId" }, "IX_Checkins_EmployeeID");

                    b.ToTable("Checkins");
                });

            modelBuilder.Entity("Domain.Entities.DailyReport", b =>
                {
                    b.Property<long>("ReportId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("ReportID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("ReportId"));

                    b.Property<long>("EmployeeId")
                        .HasColumnType("bigint")
                        .HasColumnName("EmployeeID");

                    b.Property<DateTime?>("FinalizedTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("GeneralNotes")
                        .HasColumnType("text");

                    b.Property<bool>("IsFinalized")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("ReportDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<decimal?>("TotalWorkHours")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<string>("WorkStatus")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("ReportId")
                        .HasName("PK__DailyRep__D5BD48E5FDBC9777");

                    b.HasIndex(new[] { "EmployeeId", "ReportDate" }, "UQ_DailyReports_Employee_Date")
                        .IsUnique();

                    b.ToTable("DailyReports");
                });

            modelBuilder.Entity("Domain.Entities.DailyReportCompletedTask", b =>
                {
                    b.Property<long>("ReportCompletedTaskId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("ReportCompletedTaskID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("ReportCompletedTaskId"));

                    b.Property<string>("CompletionDescription")
                        .HasColumnType("text");

                    b.Property<long>("ReportId")
                        .HasColumnType("bigint")
                        .HasColumnName("ReportID");

                    b.Property<long>("TaskId")
                        .HasColumnType("bigint")
                        .HasColumnName("TaskID");

                    b.HasKey("ReportCompletedTaskId")
                        .HasName("PK__DailyRep__77D00B9D3609CD06");

                    b.HasIndex(new[] { "TaskId" }, "IX_DailyReport_CompletedTasks_TaskID");

                    b.HasIndex(new[] { "ReportId", "TaskId" }, "UQ_ReportCompletedTasks_Report_Task")
                        .IsUnique();

                    b.ToTable("DailyReport_CompletedTasks", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.DailyReportPlannedTask", b =>
                {
                    b.Property<long>("ReportPlannedTaskId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("ReportPlannedTaskID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("ReportPlannedTaskId"));

                    b.Property<string>("PlannedDescription")
                        .HasColumnType("text");

                    b.Property<long>("ReportId")
                        .HasColumnType("bigint")
                        .HasColumnName("ReportID");

                    b.Property<long>("TaskId")
                        .HasColumnType("bigint")
                        .HasColumnName("TaskID");

                    b.HasKey("ReportPlannedTaskId")
                        .HasName("PK__DailyRep__BF13C8980D7F5F7A");

                    b.HasIndex(new[] { "TaskId" }, "IX_DailyReport_PlannedTasks_TaskID");

                    b.HasIndex(new[] { "ReportId", "TaskId" }, "UQ_ReportPlannedTasks_Report_Task")
                        .IsUnique();

                    b.ToTable("DailyReport_PlannedTasks", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.DailyWorkSummary", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("EmployeeId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("FirstCheckin")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsEarlyDeparture")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsFullDay")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsHalfDay")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsLateArrival")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsUnderHours")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastCheckout")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<decimal>("TotalCalculatedHours")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<DateTime>("WorkDate")
                        .HasColumnType("date");

                    b.HasKey("Id")
                        .HasName("PK__DailyWor__3214EC072063D57A");

                    b.HasIndex(new[] { "EmployeeId" }, "IX_DailyWorkSummary_EmployeeId");

                    b.ToTable("DailyWorkSummary", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Department", b =>
                {
                    b.Property<long>("DepartmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("DepartmentId"));

                    b.Property<string>("DepartmentName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.HasKey("DepartmentId");

                    b.ToTable("Departments");
                });

            modelBuilder.Entity("Domain.Entities.Employee", b =>
                {
                    b.Property<long>("EmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("EmployeeID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("EmployeeId"));

                    b.Property<string>("Address")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("timestamp without time zone");

                    b.Property<long?>("DepartmentId")
                        .HasColumnType("bigint");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("EmploymentStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValueSql("'Active'::character varying");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Gender")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<DateTime>("HireDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<long?>("ManagerId")
                        .HasColumnType("bigint")
                        .HasColumnName("ManagerID");

                    b.Property<string>("Password")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<long>("PositionId")
                        .HasColumnType("bigint")
                        .HasColumnName("PositionID");

                    b.HasKey("EmployeeId")
                        .HasName("PK__Employee__7AD04FF1311F0C96");

                    b.HasIndex("DepartmentId");

                    b.HasIndex(new[] { "ManagerId" }, "IX_Employees_ManagerID");

                    b.HasIndex(new[] { "PositionId" }, "IX_Employees_PositionID");

                    b.HasIndex(new[] { "Email" }, "UQ__Employee__A9D1053453A29024")
                        .IsUnique();

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("Domain.Entities.EmployeeProject", b =>
                {
                    b.Property<long>("EmployeeId")
                        .HasColumnType("bigint");

                    b.Property<long>("ProjectId")
                        .HasColumnType("bigint");

                    b.HasKey("EmployeeId", "ProjectId");

                    b.HasIndex("ProjectId");

                    b.ToTable("EmployeeProjects");
                });

            modelBuilder.Entity("Domain.Entities.EmployeesList", b =>
                {
                    b.Property<long>("TaskId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("TaskID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("TaskId"));

                    b.Property<long?>("AssignedToEmployeeId")
                        .HasColumnType("bigint")
                        .HasColumnName("AssignedToEmployeeID");

                    b.Property<DateTime?>("CompletionDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("CreationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValueSql("'Normal'::character varying");

                    b.Property<string>("RelatedProject")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValueSql("'Not Started'::character varying");

                    b.Property<string>("TaskName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("TaskId")
                        .HasName("PK__Tasks__7C6949D199CAF273");

                    b.HasIndex(new[] { "AssignedToEmployeeId" }, "IX_EmployeesList_AssignedToEmployeeID");

                    b.ToTable("EmployeesList", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Position", b =>
                {
                    b.Property<long>("PositionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("PositionID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("PositionId"));

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("PositionName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("PositionId")
                        .HasName("PK__Position__60BB9A59D6236541");

                    b.HasIndex(new[] { "PositionName" }, "UQ__Position__E46AEF4299F9F60F")
                        .IsUnique();

                    b.ToTable("Positions");
                });

            modelBuilder.Entity("Domain.Entities.Project", b =>
                {
                    b.Property<long>("ProjectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("ProjectId"));

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("ProjectName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ProjectId");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("Domain.Entities.WorkPlan", b =>
                {
                    b.Property<long>("WorkPlanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("WorkPlanId"));

                    b.Property<DateTime?>("CompletionDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<long>("EmployeeId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("PlannedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("TaskDescription")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("WorkPlanId");

                    b.HasIndex(new[] { "EmployeeId" }, "IX_WorkPlans_EmployeeId");

                    b.ToTable("WorkPlans");
                });

            modelBuilder.Entity("Domain.Entities.WorkSchedule", b =>
                {
                    b.Property<long>("WorkScheduleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("WorkScheduleID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("WorkScheduleId"));

                    b.Property<long>("EmployeeId")
                        .HasColumnType("bigint")
                        .HasColumnName("EmployeeID");

                    b.Property<string>("Notes")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime>("ScheduleDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("ScheduleType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("WorkScheduleId")
                        .HasName("PK__WorkSche__C6AC635EC0F1DC14");

                    b.HasIndex(new[] { "EmployeeId", "ScheduleDate" }, "UQ_WorkSchedules_Employee_Date")
                        .IsUnique();

                    b.ToTable("WorkSchedules");
                });

            modelBuilder.Entity("Domain.Entities.Checkin", b =>
                {
                    b.HasOne("Domain.Entities.Employee", "Employee")
                        .WithMany("Checkins")
                        .HasForeignKey("EmployeeId")
                        .IsRequired()
                        .HasConstraintName("FK_Checkins_Employees");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("Domain.Entities.DailyReport", b =>
                {
                    b.HasOne("Domain.Entities.Employee", "Employee")
                        .WithMany("DailyReports")
                        .HasForeignKey("EmployeeId")
                        .IsRequired()
                        .HasConstraintName("FK_DailyReports_Employees");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("Domain.Entities.DailyReportCompletedTask", b =>
                {
                    b.HasOne("Domain.Entities.DailyReport", "Report")
                        .WithMany("DailyReportCompletedTasks")
                        .HasForeignKey("ReportId")
                        .IsRequired()
                        .HasConstraintName("FK_ReportCompletedTasks_Report");

                    b.HasOne("Domain.Entities.EmployeesList", "Task")
                        .WithMany("DailyReportCompletedTasks")
                        .HasForeignKey("TaskId")
                        .IsRequired()
                        .HasConstraintName("FK_ReportCompletedTasks_EmployeesList");

                    b.Navigation("Report");

                    b.Navigation("Task");
                });

            modelBuilder.Entity("Domain.Entities.DailyReportPlannedTask", b =>
                {
                    b.HasOne("Domain.Entities.DailyReport", "Report")
                        .WithMany("DailyReportPlannedTasks")
                        .HasForeignKey("ReportId")
                        .IsRequired()
                        .HasConstraintName("FK_ReportPlannedTasks_Report");

                    b.HasOne("Domain.Entities.EmployeesList", "Task")
                        .WithMany("DailyReportPlannedTasks")
                        .HasForeignKey("TaskId")
                        .IsRequired()
                        .HasConstraintName("FK_ReportPlannedTasks_EmployeesList");

                    b.Navigation("Report");

                    b.Navigation("Task");
                });

            modelBuilder.Entity("Domain.Entities.DailyWorkSummary", b =>
                {
                    b.HasOne("Domain.Entities.Employee", "Employee")
                        .WithMany("DailyWorkSummaries")
                        .HasForeignKey("EmployeeId")
                        .IsRequired()
                        .HasConstraintName("FK_DailyWorkSummary_Employees");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("Domain.Entities.Employee", b =>
                {
                    b.HasOne("Domain.Entities.Department", "Department")
                        .WithMany("Employees")
                        .HasForeignKey("DepartmentId");

                    b.HasOne("Domain.Entities.Employee", "Manager")
                        .WithMany("InverseManager")
                        .HasForeignKey("ManagerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_Employees_Manager");

                    b.HasOne("Domain.Entities.Position", "Position")
                        .WithMany("Employees")
                        .HasForeignKey("PositionId")
                        .IsRequired()
                        .HasConstraintName("FK_Employees_Positions");

                    b.Navigation("Department");

                    b.Navigation("Manager");

                    b.Navigation("Position");
                });

            modelBuilder.Entity("Domain.Entities.EmployeeProject", b =>
                {
                    b.HasOne("Domain.Entities.Employee", "Employee")
                        .WithMany("EmployeeProjects")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Project", "Project")
                        .WithMany("EmployeeProjects")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Domain.Entities.EmployeesList", b =>
                {
                    b.HasOne("Domain.Entities.Employee", "AssignedToEmployee")
                        .WithMany("EmployeesLists")
                        .HasForeignKey("AssignedToEmployeeId")
                        .HasConstraintName("FK_EmployeesList_Employees");

                    b.Navigation("AssignedToEmployee");
                });

            modelBuilder.Entity("Domain.Entities.WorkPlan", b =>
                {
                    b.HasOne("Domain.Entities.Employee", "Employee")
                        .WithMany("WorkPlans")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_WorkPlan_Employee");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("Domain.Entities.WorkSchedule", b =>
                {
                    b.HasOne("Domain.Entities.Employee", "Employee")
                        .WithMany("WorkSchedules")
                        .HasForeignKey("EmployeeId")
                        .IsRequired()
                        .HasConstraintName("FK_WorkSchedules_Employees");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("Domain.Entities.DailyReport", b =>
                {
                    b.Navigation("DailyReportCompletedTasks");

                    b.Navigation("DailyReportPlannedTasks");
                });

            modelBuilder.Entity("Domain.Entities.Department", b =>
                {
                    b.Navigation("Employees");
                });

            modelBuilder.Entity("Domain.Entities.Employee", b =>
                {
                    b.Navigation("Checkins");

                    b.Navigation("DailyReports");

                    b.Navigation("DailyWorkSummaries");

                    b.Navigation("EmployeeProjects");

                    b.Navigation("EmployeesLists");

                    b.Navigation("InverseManager");

                    b.Navigation("WorkPlans");

                    b.Navigation("WorkSchedules");
                });

            modelBuilder.Entity("Domain.Entities.EmployeesList", b =>
                {
                    b.Navigation("DailyReportCompletedTasks");

                    b.Navigation("DailyReportPlannedTasks");
                });

            modelBuilder.Entity("Domain.Entities.Position", b =>
                {
                    b.Navigation("Employees");
                });

            modelBuilder.Entity("Domain.Entities.Project", b =>
                {
                    b.Navigation("EmployeeProjects");
                });
#pragma warning restore 612, 618
        }
    }
}
